### ISSUE TITLE
I get logged out a lot while working

### ISSUE THREAD

**Issue by aninternetof** [rovercode/rovercode-ui#116]
I think our token expiry time might be set a little low. Could it be made longer?

**Comment by ductape** [comment]
Which auth are you using? I had this issue when using GitHub auth, but hadn't noticed it when using email/password. That doesn't mean it's different, I just hadn't noticed it except the one day I was using GitHub auth and that kept happening to me.

**Comment by aninternetof** [comment]
Interesting note. I think I'm using email/password?

**Comment by cabarnes** [comment]
The token is issued by the backend so the configuration would need to be changed there

**Comment by aninternetof** [comment]
I wish tickets could be transferred to different projects...
