### ISSUE TITLE
Create rover list view

### ISSUE THREAD

**Issue by aninternetof** [rovercode/rovercode-ui#14]
![rover list view](https://i.imgur.com/xIKUOfc.jpg)

**Comment by aninternetof** [comment]
For the `connected` column, we could use some logic on the last check-in time on the rover model. Maybe it's connect if it have checked in in the last 30 seconds?

**Comment by aninternetof** [comment]
The `connected` checkmark or X could use [Semantic UI positive negative table cell states](https://react.semantic-ui.com/collections/table/#states-positive-negative). They can be the default green/red (not in the color scheme, but more clear. I just didn't have green or red pens :-) )

**Comment by aninternetof** [comment]
I'm on the fence about whether we need any paging. Doesn't seem like anybody would have pages and pages of rovers. On the other hand, it might not be bad practice. Anybody else have thoughts?

**Comment by aninternetof** [comment]
The inspiration for the `ROVERS` page title bar is here: https://scratch.mit.edu/explore/projects/all

**Comment by aninternetof** [comment]
The color of the `Curiousity`, `Luna` etc links is the tertiary purple color. (sorry, I wrote it in black first and tried to fix it)

**Comment by cabarnes** [comment]
I think pagination is ok. The API will already do it, so we might as well plan for it. The search is a little more complicated and maybe something that we would add later if the amount of rovers starts to become substantial enough for users. The only other things would be filtering and sorting. It seems like filtering for `connected` might be useful and sorting by name and date as well.

**Comment by aninternetof** [comment]
https://beta.rovercode.com/api/v1/rovers/
