### ISSUE TITLE
Create mission control

### ISSUE THREAD

**Issue by aninternetof** [rovercode/rovercode-ui#20]
![mission control mock](https://i.imgur.com/fmry1HN.jpg)

**Comment by aninternetof** [comment]
Missing from mock: logo in leftmost corner of menu bar

**Comment by aninternetof** [comment]
I think the "Connect to a rover" link should open a model?

**Comment by aninternetof** [comment]
A "Name this program" modal should show initially, similar to old design.

**Comment by aninternetof** [comment]
"Remix this program" should make a copy of the program and bring up the "Name this program" modal to give the copy a new name.

**Comment by cabarnes** [comment]
@aninternetof I think this is complete as well now that the active rover selection has been added?

**Comment by aninternetof** [comment]
Agree! Closing.
