### ISSUE TITLE
Create Rover websocket connections

### ISSUE THREAD

**Issue by aninternetof** [rovercode/rovercode-ui#59]
We imagine separate websocket connections to each Rover's endpoint, allowing connection status updates, sensor updates, and motor commands.

**Comment by aninternetof** [comment]
![image](https://user-images.githubusercontent.com/976857/54033861-6e62ca00-4183-11e9-8115-913423d21c60.png)

**Comment by aninternetof** [comment]
Above is an image of the architecture I'd like to propose.

On the left side, the Workspace instantiates a new class called RoverCommandGenerator. It the method `generateMotorCommand`, which the Workspace passes into the BlocklyApi instance, so that the BlocklyApi can call it like it does `writeToConsole` or anything else.

This `generateMotorCommand` method calls triggers two Redux actions: `setCommand(someCommand)` and `setCommandHandled(false)`. This store the motor command in Redux, and set a `commandHandled` flag to false.

On the right side, MissionControl instantiates a list of a new component called RoverConnection. This is a rectangular tile which houses the name of the rover, and a light to indicate if the rover is online. Each tile knows the clientId of its rover. **Each instance of RoverConnection creates and manages its own WebSocket connection on creation**.

When the user clicks a tile, the tile triggers an action to set the global `selectedRoverClientId` in Redux. (Sorry, this is not shown in the diagram.)

All the RoverConnection tiles watch the Redux `command` and `commandIsHandled` properties, but only the take any action if their clientId matches the global `selectedRoverClientId`. If a tile is the selected rover, it
* Triggers the `changeSensorState` actions when it receives sensor messages over its websocket.
* Sends motor commands out its websocket when it sees that `commandIsHandled` is false. After sending the message, it clears the `commandIsHandled` flag by setting it to true again.

In this architecture, we've used Redux to create a pub-sub relationship between the BlocklyApi and the Rover connections. It seemed like the only other option was using Refs (which are discouraged) or Hooks (which are new).

What do you think?

**Comment by aninternetof** [comment]
Here is our WebSocket protocol: https://contributor-docs.rovercode.com/rovercode/development/websocket-protocol.html

**Comment by aninternetof** [comment]
Let's nail down some terminology:

`online`: the Rover is powered on, connected to its WebSocket endpoint, and sending out heartbeats. Many rovers for a single user can be online at one time.
`selected`: The user has selected this Rover to control and receive sensor events from. Only one rover can be selected at a time.

**Comment by ductape** [comment]
> Each instance of RoverConnection creates and manages its own WebSocket connection on creation.

So with this architecture, are we defining a 1 user : many rovers in the web/ui, but 1 user : 1 rover on the rover? E.g. a given rover will only ever belong to one user (as determined by the ENV file), but one user can have many rovers? E.g. there it would be technically impossible to share a rover between users?

> Let's nail down some terminology:

Agreed on the `online` and `selected` terminology. I think I would also be fine with `selected` or `active`. I'm assuming `offline` is also a state that is handled, but not worth clarifying since we are probably in agreement with its definition? 😛 

> automatic timer to shut off after 8 seconds, but a heartbeat that comes every 4 seconds

We should modify the heartbeat API to pass in a timeout value-- the number of seconds until the next expected heartbeat. Then the timeout can be double that programmatically so the rover and backend/UI can't get out of sync.  We can send 4 seconds in the normal case of the parameter.

**Comment by aninternetof** [comment]
Good question! Sharing is super important, and this architecture will allow sharing. In the backend, we'll create a many-to-many relationship between users and rovers. A user will be able to register a rover, put its .env file on the rover, then share that rover with other users. When its shared, the OAuth "app" that represents rover credentials will be copied to the other user's user model. The other user will be able to use that rover with no changes or additions needed to the .env file on the rover. [I have a work-in-progress branch of the backend changes for this.](https://github.com/rovercode/rovercode-web/commit/b7be31de454793be714d0eedbdf10fc266cc82b0).

**Comment by aninternetof** [comment]
Good idea -- I like `active` better than `selected. So let's go with:

* Online/Offline - Is the rover on and sending heartbeats to the WebSocket server?
* Active/Inactive - Is this the rover that the user has selected?

**Comment by aninternetof** [comment]
> We should modify the heartbeat API to pass in a timeout value-- the number of seconds until the next expected heartbeat. 

This is a great idea. I'll add it to the protocol doumentation.

**Comment by cabarnes** [comment]
I think we're going to need some kind of queue in Redux for the commands to send to the rover. Otherwise, Blockly might change the `command` faster than we can send it out via the web socket.

**Comment by aninternetof** [comment]
That's a good point. Do you think a queue is possible in Redux?

**Comment by cabarnes** [comment]
It seems like at its most basic, it could just be an array. But, I'll see if there's a better storage option when using Redux
